### ISSUE TITLE
Apache2buddy rely only on netstat

### ISSUE THREAD

**Issue by sumitgarg44** [rackerlabs/useful-scripts#38]
As OS vendors are moving towards 'ss' than netstat in latest releases. I believe it will be worth to add ss support in apache2buddy script.

**Comment by LukeShirnia** [comment]
Hey @sumitgarg44 thanks for raising the issue. Apache2buddy isn't actually maintained by ourselves, it's forked from upstream (https://github.com/richardforth/apache2buddy), we then just validate/verify the code is ok. It's definitely worth raising the issue there as I think Richard is still actively developing the tool.

**Comment by sumitgarg44** [comment]
Thank you Luke, I have raised issue on upstream. Closing this now.
